### ISSUE TITLE
loading freecad addon "fasteners" will fail

### ISSUE THREAD

**Issue by Ventusfahrer** [FreeCAD/FreeCAD-snap#132]
Hi there!

I was installing the Freecad AddOn Fasteners from the AddOn store.

When trying to load the Addon via Edit -> Preferences -> Workbenches -> Press Load Button behind Fasteners, the UI fires a popup

![image](https://github.com/user-attachments/assets/6174421f-06c1-4f34-8f33-0590c406fb0c)

The terminal output contains a little more information:

```
freecad
FreeCAD 1.1.0, Libs: 1.1.0devR39100 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Adding snap-specific PYTHONPATH to sys.path: /home/peter/snap/freecad/common/.local/lib/python3.10/site-packages:/snap/freecad/1180/lib/python3.10/site-packages:/snap/freecad/1180/usr/lib/python3/dist-packages
Qt: Session management error: Could not open network socket
connect failed: No such file or directory
'NoneType' object has no attribute 'setCheckable'
Traceback (most recent call last):
  File "/home/peter/snap/freecad/common/Mod/fasteners/./InitGui.py", line 112, in Activated
    FastenerBase.InitCheckables()
  File "/home/peter/snap/freecad/common/Mod/fasteners/./FastenerBase.py", line 892, in InitCheckables
    matchOuterButton.setCheckable(True)
```

freecad version is:

```
$ snap list freecad
Name     Version        Revision  Tracking     Herausgeber  Hinweise
freecad  1.1-g8865450a  1180      latest/edge  freecad-org  -

```

The corresponding weekly appimage from the download aerea is working fine.

kind regards

Peter

**Comment by luzpaz** [comment]
@furgo16 can you reproduce? (I'm having issues with Snap ATM and can't test)

**Comment by Ventusfahrer** [comment]
my current  OS is: 
Ubuntu 24.10 with all current updates installed.
I can reproduce the problem on two computers (desktop and noteboot) both running with the same OS-Version

**Comment by luzpaz** [comment]
Full [About](https://wiki.freecad.org/About) info please

**Comment by Ventusfahrer** [comment]
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39100 (Git) Snap 1180
Build type: Release
Branch: main
Hash: 8865450a3e14220925e0e449c0f1f79056b4fb89
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * fasteners 0.5.29
  * Manipulator 1.5.7

**Comment by furgo16** [comment]
@luzpaz thanks for the heads up. I can reproduce:

```
'NoneType' object has no attribute 'setCheckable'
Traceback (most recent call last):
  File "/home/$HOME/snap/freecad/common/Mod/fasteners/./InitGui.py", line 112, in Activated
    FastenerBase.InitCheckables()
  File "/home/$HOME/snap/freecad/common/Mod/fasteners/./FastenerBase.py", line 892, in InitCheckables
    matchOuterButton.setCheckable(True)
```

```
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39176 (Git) Snap 1189
Build type: Release
Branch: main
Hash: 45d3864942c6928cec7dc18f95b1f222485756e5
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * fasteners 0.5.30
  * ezydxf
  * Assembly4 0.50.15
```

I'll check the PPA build next.

**Comment by furgo16** [comment]
This is not specific to the snap package. I get the same behavior from the daily PPA (.deb package):

```
'NoneType' object has no attribute 'setCheckable'
Traceback (most recent call last):
  File "/home/$HOME/.local/share/FreeCAD/Mod/fasteners/./InitGui.py", line 112, in Activated
    FastenerBase.InitCheckables()
  File "/home/$HOME/.local/share/FreeCAD/Mod/fasteners/./FastenerBase.py", line 892, in InitCheckables
    matchOuterButton.setCheckable(True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39175 (Git)
Build type: Release
Branch: main
Hash: 46831f4c86a1679d48f63273b92cd755522e42f9
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * WikiPropertiesGenerator.FCMacro
  * fasteners 0.5.30
```

@luzpaz is it worth moving this issue to the main FreeCAD repository, or to the Fasteners workbench one?

**Comment by luzpaz** [comment]
@furgo16 sorry, I'll transfer it now.
