### ISSUE TITLE
Snap Store upload fails: This login method is not longer supported                         

### ISSUE THREAD

**Issue by ppd** [FreeCAD/FreeCAD-snap#22]
```shell
 Traceback (most recent call last):
  File "/snap/snapcraft/7664/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/snapcraft/cli.py", line 179, in run
    dispatcher.run()
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/craft_cli/dispatcher.py", line 406, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/snapcraft/commands/upload.py", line 89, in run
    client.verify_upload(snap_name=snap_name)
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/snapcraft/commands/store/client.py", line 344, in verify_upload
    self.request(
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/snapcraft/commands/store/client.py", line 217, in request
    return self.store_client.request(*args, **kwargs)
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/craft_store/ubuntu_one_store_client.py", line 137, in request
    self._refresh_token()
  File "/snap/snapcraft/7664/lib/python3.8/site-packages/craft_store/ubuntu_one_store_client.py", line 70, in _refresh_token
    macaroons = json.loads(self._auth.get_credentials())
  File "/snap/snapcraft/7664/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/snap/snapcraft/7664/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/snapcraft/7664/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
This login method is not longer supported      
```

https://github.com/FreeCAD/FreeCAD-snap/runs/6891164630

**Comment by ppd** [comment]
Should've been fixed with https://github.com/snapcore/snapcraft/releases/tag/7.0.4
Let's see if that works.
